import express from "express";
import bodyParser from "body-parser";

const app = express();
const port = 3000;

const state = {
  websiteTitle: "Super Blog",
};

app.use(bodyParser.urlencoded({ extended: true }));
app.use(express.static("public"));

app.listen(port, () => {
  console.log(`Server started on port ${port}`);
});

let currentMaxID = 0; // Increment this every time a post is made

class Post {
  constructor(postID, username, title, content, footnotes) {
    this.postID = postID;
    this.postDate = new Date().toDateString();
    this.username = username;
    this.title = title;
    this.content = content;
    this.footnotes = footnotes;
  }
}

// let posts = []; // An array of Post objects

let posts = [
  // Test data generated by ChatGPT
  new Post(
    1,
    "john_doe",
    "My First Post",
    "This is the content of my first post.",
    "Note 1, Note 2"
  ),
  new Post(
    2,
    "jane_smith",
    "A Day in the Life",
    "This is a post about my daily routine.",
    "Note A, Note B"
  ),
  new Post(
    3,
    "alice_wonder",
    "Exploring JavaScript",
    "JavaScript is a powerful language for web development.",
    "Footnote X"
  ),
  new Post(
    4,
    "bob_jones",
    "A Guide to CSS",
    "CSS is essential for styling web pages.",
    "Tip 1, Tip 2"
  ),
  new Post(
    5,
    "mary_doe",
    "My Travel Adventures",
    "I visited five countries last year, and here are my stories.",
    "Travel Tip"
  ),
  new Post(
    6,
    "charlie_brown",
    "Cooking 101",
    "Cooking is fun and easy. Here are some simple recipes.",
    "Note 1, Note 2, Note 3"
  ),
  new Post(
    7,
    "emma_white",
    "Fitness Tips for Beginners",
    "Get started with fitness with these easy-to-follow tips.",
    "Tip A, Tip B"
  ),
];
currentMaxID = 7; // set to 7 to account for test data


function sendPost(username, title, content, footnotes) {
  const newPostID = ++currentMaxID;
  const newPost = new Post(newPostID, username, title, content, footnotes);
  console.log(newPost);

  posts.push(newPost);
  return newPostID;
}

// Render the Home page
app.get("/", (req, res) => {
  res.locals.websiteTitle = state.websiteTitle;
  res.locals.posts = posts;
  res.render("index.ejs");
});

// Render the post creation page
app.get("/post/create", (req, res) => {
  res.locals.websiteTitle = state.websiteTitle;
  res.render("post_create.ejs");
});

app.post("/post/create", (req, res) => {
  let postID = sendPost(
    req.body.username,
    req.body.title,
    req.body.content,
    req.body.footnotes
  );
  res.redirect(`/post/${postID}`);
});

// Render a given post's page
app.get("/post/:postID", (req, res) => {
  res.locals.websiteTitle = state.websiteTitle;
  res.locals.post = posts[req.params["postID"] - 1]; // arrays are 0-indexed
  console.log(res.locals.post);
  res.render("post_view.ejs");
});
